{
 "title": "Node Exporter Overview",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Basic CPU / Mem / Net / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (sum by(instance) (irate(node_cpu_seconds_total{job=\"$job\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{job=\"$job\"}[$__rate_interval]))))",
     "legendFormat": "CPU Busy - {{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (avg(node_memory_MemFree_bytes{job=\"$job\"}) by (instance)) / avg(node_memory_MemTotal_bytes{job=\"$job\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=\"$job\"}[$__rate_interval])) by (instance) * 8",
     "legendFormat": "recv {{instance}}"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=\"$job\"}[$__rate_interval])) by (instance) *8",
     "legendFormat": "trans {{instance}} "
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"$job\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{job=\"$job\",device!~'rootfs'})",
     "legendFormat": "{{instance}}:{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Time Synchronized Drift",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds{job=\"$job\"}",
     "legendFormat": "Estimated error in seconds - {{instance}}"
    },
    {
     "expr": "node_timex_offset_seconds{job=\"$job\"}",
     "legendFormat": "Time offset in between local system and reference clock - {{instance}}"
    },
    {
     "expr": "node_timex_maxerror_seconds{job=\"$job\"}",
     "legendFormat": "Maximum error in seconds - {{instance}}"
    }
   ]
  },
  {
   "title": "Process schedule stats Running / Waiting",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(irate(node_schedstat_running_seconds_total{job=\"$job\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}} - seconds spent running a process"
    },
    {
     "expr": "max(irate(node_schedstat_waiting_seconds_total{job=\"$job\"}[$__rate_interval])) by (instance)",
     "legendFormat": "{{instance}} - seconds spent by processing waiting for this CPU"
    }
   ]
  },
  {
   "title": "Processes Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_procs_blocked{job=\"$job\"}",
     "legendFormat": "{{instance}} - Processes blocked waiting for I/O to complete"
    },
    {
     "expr": "node_procs_running{job=\"$job\"}",
     "legendFormat": "{{instance}} - Processes in runnable state"
    }
   ]
  }
 ]
}