{
 "title": "Nomad Jobs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Job",
    "label": "exported_job",
    "query": {
     "query": "label_values(nomad_nomad_job_summary_complete,exported_job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Allocated CPU",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (avg by(exported_job, task, task_group) (nomad_client_allocs_cpu_allocated{exported_job=~\"$Job\"})) * 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task CPU %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(exported_job, task, task_group) (nomad_client_allocs_cpu_total_percent{exported_job=~\"$Job\"})",
     "legendFormat": "{{exported_job}} -> {{task_group}} -> {{task}}"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (avg by(exported_job, task, task_group) (nomad_client_allocs_memory_allocated{exported_job=~\"$Job\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Memory %",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by(exported_job, task, task_group) (nomad_client_allocs_memory_usage{exported_job=~\"$Job\"}) / avg by(exported_job, task, task_group) (nomad_client_allocs_memory_allocated{exported_job=~\"$Job\"})) * 100",
     "legendFormat": "{{exported_job}} -> {{task_group}} -> {{task}}"
    }
   ]
  }
 ]
}